<?php

namespace App\Services\Logistics;

use App\Models\MachineService;
use App\Models\DashboardAlert;
use App\Models\MaintenanceRequest;
use App\Models\Patron;
use App\Models\User;
use App\Models\GpsLatestPosition;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class MaintenanceSchedulerService
{
    /**
     * Check machine mileage telemetry and trigger preventive maintenance alerts & requests if threshold reached.
     *
     * @param int $machineId
     * @param float $odometer
     * @param int|null $plantId
     * @return void
     */
    public function checkAndTrigger(int $machineId, float $odometer, ?int $plantId = null)
    {
        if ($plantId === null) {
            $machine = DB::table('mm_machines')->find($machineId);
            $plantId = $machine ? $machine->plant_id : null;
        }

        if (!$plantId) {
            return;
        }

        // Update active machine services with current odometer
        MachineService::where('truck_id', $machineId)
            ->where('status', 1) // status 1: active/pending check
            ->update(['current_running_km' => $odometer]);

        // Find due services (status = 1 and current_running_km >= next_service_km)
        $dueServices = MachineService::with('machine')
            ->where('truck_id', $machineId)
            ->where('status', 1)
            ->whereRaw('current_running_km >= next_service_km')
            ->get();

        foreach ($dueServices as $service) {
            DB::transaction(function () use ($service, $odometer, $plantId) {
                // 1. Generate Dashboard Alert
                $registration = $service->machine->registration ?? "Machine #{$service->truck_id}";
                
                // Get Entity ID
                $plant = DB::table('mm_plants')->find($plantId);
                $entityId = $plant ? $plant->entity_id : null;

                DashboardAlert::create([
                    'type' => 'preventive_maintenance',
                    'status' => 'active',
                    'message' => "Preventive Maintenance Alert: Vehicle {$registration} has reached {$odometer} km (Threshold: {$service->next_service_km} km). Service Type: {$service->service_type}.",
                    'plant_id' => $plantId,
                    'entity_id' => $entityId,
                    'date_time_on' => now(),
                ]);

                // 2. Select first vendor/patron from DB for foreign key constraint
                $vendor = Patron::where('plant_id', $plantId)
                    ->where(function($q) {
                        $q->whereJsonContains('patron_type', 'Vendor')
                          ->orWhereJsonContains('patron_type', 'Transporter');
                    })
                    ->first()
                    ?: Patron::whereJsonContains('patron_type', 'Vendor')
                       ->orWhereJsonContains('patron_type', 'Transporter')
                       ->first()
                    ?: Patron::first();

                $vendorId = $vendor ? $vendor->id : 1;

                // Select first user as responsible
                $responsible = User::first();
                $responsibleId = $responsible ? $responsible->id : 1;

                // 3. Auto-generate draft maintenance request
                MaintenanceRequest::create([
                    'name' => "PM Due - {$registration} (Type {$service->service_type})",
                    'description' => "Automated Preventive Maintenance Request generated by GPS Odometer Telemetry.\n" .
                                     "Current Odometer: " . number_format($odometer, 2) . " km.\n" .
                                     "Service Threshold: " . number_format($service->next_service_km, 2) . " km.\n" .
                                     "Service Type: {$service->service_type}.",
                    'machine_id' => $service->truck_id,
                    'plant_id' => $plantId,
                    'max_idle_days' => '5',
                    'inventory_req_lines' => 'N/A',
                    'maintanence_type' => 1, // 1 for Preventive/Scheduled
                    'service_km' => $service->next_service_km,
                    'priority' => 2, // Medium
                    'responsible_id' => $responsibleId,
                    'repair_location' => 'Main Workshop',
                    'repair_vendor_id' => $vendorId,
                    'status' => 0, // 0 = Draft/Pending
                    'bill_status' => 0,
                    'dead_line' => now()->addDays(7),
                    'start_date' => now(),
                    'end_date' => now()->addDays(1),
                    'discount_amount' => 0.00,
                    'shipping_charges' => 0.00,
                    'adjustment' => 0.00,
                    'rounding_value' => 0.00,
                ]);

                // 4. Update status of the service trigger so we don't duplicate alerts (status 2 = Due/Alerted)
                $service->update([
                    'status' => 2,
                    'notes' => ($service->notes ? $service->notes . "\n" : "") . "Alerted at odometer: {$odometer} km"
                ]);
            });
        }
    }

    /**
     * Scan all active services in the database and synchronize their current_running_km with the latest odometer reading.
     *
     * @return int Number of updated services
     */
    public function syncAllActiveServices(): int
    {
        $activeServices = MachineService::where('status', 1)->get();
        $updatedCount = 0;

        foreach ($activeServices as $service) {
            // Find latest odometer from gps cache
            $latest = GpsLatestPosition::where('machine_id', $service->truck_id)->first();
            if ($latest && $latest->odometer !== null) {
                $this->checkAndTrigger($service->truck_id, (float)$latest->odometer, $service->plant_id);
                $updatedCount++;
            }
        }

        return $updatedCount;
    }
}
