<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>e-Way Bill - {{ $data['ewb_no'] ?? 'Document' }}</title>
    @include('pdfs.partials._common_styles')
    <style>
        @page {
            size: A4 portrait;
            margin: 10mm 15mm;
        }

        body {
            font-family: Arial, Helvetica, 'DejaVu Sans', sans-serif;
            color: #111827;
            background: #fff;
            font-size: 11px;
            margin: 0;
            padding: 0;
        }

        .ewb-box {
            width: 100%;
            max-width: 780px;
            margin: 0 auto;
            border: 1px solid #94a3b8;
            background: #fff;
            padding: 18px 22px;
            box-sizing: border-box;
        }

        /* HEADER */
        .ewb-header {
            text-align: center;
            margin-bottom: 8px;
        }

        .ewb-title {
            font-size: 18px;
            font-weight: 700;
            color: #111827;
            margin: 0 0 8px 0;
            text-align: center;
        }

        .ewb-qr-wrap {
            text-align: center;
            margin-bottom: 12px;
        }

        .ewb-qr-wrap img {
            width: 95px;
            height: 95px;
            display: inline-block;
        }

        /* TABLES */
        .ewb-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }

        .ewb-table tr {
            border-bottom: 1px solid #cbd5e1;
        }

        .ewb-table tr:last-child {
            border-bottom: 1px solid #94a3b8;
        }

        .ewb-table td {
            padding: 5px 8px;
            vertical-align: middle;
            font-size: 10.5px;
            line-height: 1.35;
        }

        .ewb-table .td-lbl {
            width: 38%;
            color: #374151;
            font-weight: 500;
        }

        .ewb-table .td-val {
            width: 62%;
            color: #000;
            font-weight: 700;
        }

        /* SECTION TITLES */
        .section-title {
            font-size: 11.5px;
            font-weight: 700;
            color: #111827;
            margin: 12px 0 6px 0;
            padding-left: 2px;
        }

        /* PART B TABLE */
        .part-b-table {
            width: 100%;
            border-collapse: collapse;
            border: 1px solid #94a3b8;
            margin-top: 4px;
            margin-bottom: 14px;
        }

        .part-b-table th,
        .part-b-table td {
            border: 1px solid #cbd5e1;
            padding: 6px 6px;
            font-size: 10px;
            text-align: center;
            vertical-align: middle;
        }

        .part-b-table th {
            background: #f8fafc;
            color: #111827;
            font-weight: 700;
        }

        .part-b-table td {
            color: #111827;
            font-weight: 600;
        }

        /* BARCODE SECTION */
        .barcode-section {
            text-align: center;
            margin: 14px 0 10px 0;
        }

        .barcode-wrap {
            display: inline-block;
            text-align: center;
        }

        .barcode-num {
            font-family: monospace;
            font-size: 10px;
            font-weight: 700;
            color: #111827;
            margin-top: 2px;
            letter-spacing: 0.5px;
        }

        /* FOOTER NOTE */
        .disclaimer-note {
            font-size: 8.5px;
            color: #4b5563;
            margin-top: 8px;
            padding-top: 4px;
        }
    </style>
</head>
<body>

@include('pdfs.partials._print_actions')

<div class="ewb-box">
    <!-- Top Header -->
    <div class="ewb-header">
        <div class="ewb-title">e-Way Bill</div>
        <div class="ewb-qr-wrap">
            <img 
                src="https://api.qrserver.com/v1/create-qr-code/?size=110x110&data={{ urlencode($data['qr_data'] ?? $data['ewb_no'] ?? '') }}" 
                alt="e-Way Bill QR Code" 
            />
        </div>
    </div>

    <!-- Main E-Way Bill Details Table -->
    <table class="ewb-table">
        <tr>
            <td class="td-lbl">E-Way Bill No:</td>
            <td class="td-val">{{ $data['ewb_no_formatted'] ?? chunk_split($data['ewb_no'] ?? '', 4, ' ') }}</td>
        </tr>
        <tr>
            <td class="td-lbl">E-Way Bill Date:</td>
            <td class="td-val">{{ $data['ewb_date'] ?? '' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">Generated By:</td>
            <td class="td-val">{{ $data['generated_by'] ?? '' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">Valid From:</td>
            <td class="td-val">{{ $data['valid_from'] ?? '' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">Valid Until:</td>
            <td class="td-val">{{ $data['valid_until'] ?? '' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">Portal:</td>
            <td class="td-val">{{ $data['portal'] ?? '1' }}</td>
        </tr>
    </table>

    <!-- Part - A -->
    <div class="section-title">Part - A</div>
    <table class="ewb-table">
        <tr>
            <td class="td-lbl">GSTIN of Supplier</td>
            <td class="td-val">{{ $data['gstin_supplier'] ?? '' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">Place of Dispatch</td>
            <td class="td-val">{{ $data['place_of_dispatch'] ?? '' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">GSTIN of Recipient</td>
            <td class="td-val">{{ $data['gstin_recipient'] ?? '' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">Place of Delivery</td>
            <td class="td-val">{{ $data['place_of_delivery'] ?? '' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">Document No.</td>
            <td class="td-val">{{ $data['doc_no'] ?? '' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">Document Date</td>
            <td class="td-val">{{ $data['doc_date'] ?? '' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">Transaction Type:</td>
            <td class="td-val">{{ $data['transaction_type'] ?? 'Regular' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">Value of Goods</td>
            <td class="td-val">{{ $data['value_of_goods'] ?? '' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">HSN Code</td>
            <td class="td-val">{{ $data['hsn_code'] ?? '' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">Reason for Transportation</td>
            <td class="td-val">{{ $data['reason_for_transport'] ?? 'Outward - Supply' }}</td>
        </tr>
        <tr>
            <td class="td-lbl">Transporter</td>
            <td class="td-val">{{ $data['transporter'] ?? '' }}</td>
        </tr>
    </table>

    <!-- Part - B -->
    <div class="section-title">Part - B</div>
    <table class="part-b-table">
        <thead>
            <tr>
                <th style="width: 8%;">Mode</th>
                <th style="width: 22%;">Vehicle / Trans Doc No & Dt.</th>
                <th style="width: 12%;">From</th>
                <th style="width: 18%;">Entered Date</th>
                <th style="width: 18%;">Entered By</th>
                <th style="width: 11%;">CEWB No.<br>(If any)</th>
                <th style="width: 11%;">Multi Veh.Info<br>(If any)</th>
                <th style="width: 6%;">Portal</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $data['part_b']['mode'] ?? 'Road' }}</td>
                <td>{{ $data['part_b']['vehicle_no'] ?? '-' }}</td>
                <td>{{ $data['part_b']['from'] ?? '-' }}</td>
                <td>{{ $data['part_b']['entered_date'] ?? '-' }}</td>
                <td>{{ $data['part_b']['entered_by'] ?? '-' }}</td>
                <td>{{ $data['part_b']['cewb_no'] ?? '-' }}</td>
                <td>{{ $data['part_b']['multi_veh_info'] ?? '-' }}</td>
                <td>{{ $data['part_b']['portal'] ?? '1' }}</td>
            </tr>
        </tbody>
    </table>

    <!-- Bottom Barcode -->
    <div class="barcode-section">
        <div class="barcode-wrap">
            {!! $data['barcode_svg'] ?? '' !!}
            <div class="barcode-num">{{ $data['ewb_no'] ?? '' }}</div>
        </div>
    </div>

    <!-- Disclaimer Note -->
    <div class="disclaimer-note">
        Note*: If any discrepancy in information please try after sometime.
    </div>
</div>

</body>
</html>
